[%General]
language=en_US
recentFileList=/var/home/hugh/Insync/whelanh@gmail.com/Google Drive/Sample/FedModel.sqlite

[MainWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\xff\xff\xff\xf5\xff\xff\xff\xcf\0\0\x4\xfc\0\0\x5\b\0\0\0\0\0\0\0\0\0\0\x4\xf1\0\0\x4\xfd\0\0\0\0\0\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\x4\xf1\0\0\x4\xfd)
openTabs=structure browser pragmas query
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\x1\0\0\0\x1\0\0\x2.\0\0\x4\xa9\xfc\x2\0\0\0\x2\xfb\0\0\0\x10\0\x64\0o\0\x63\0k\0\x45\0\x64\0i\0t\x1\0\0\0<\0\0\x2\xe\0\0\0\xba\0\xff\xff\xff\xfc\0\0\x2P\0\0\x2\x95\0\0\0\xff\x1\0\0\x1f\xfa\0\0\0\x3\x2\0\0\0\x4\xfb\0\0\0\xe\0\x64\0o\0\x63\0k\0L\0o\0g\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\x80\0\xff\xff\xff\xfb\0\0\0\x10\0\x64\0o\0\x63\0k\0P\0l\0o\0t\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\xdf\0\xff\xff\xff\xfb\0\0\0\x14\0\x64\0o\0\x63\0k\0S\0\x63\0h\0\x65\0m\0\x61\x1\0\0\0\0\xff\xff\xff\xff\0\0\0Z\0\xff\xff\xff\xfb\0\0\0\x14\0\x64\0o\0\x63\0k\0R\0\x65\0m\0o\0t\0\x65\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\xc9\0\xff\xff\xff\0\0\x2\xbe\0\0\x4\xa9\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x12\0t\0o\0o\0l\0\x62\0\x61\0r\0\x44\0\x42\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x1c\0t\0o\0o\0l\0\x62\0\x61\0r\0P\0r\0o\0j\0\x65\0\x63\0t\x1\0\0\x2\xd7\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x1c\0t\0o\0o\0l\0\x62\0\x61\0r\0\x45\0x\0t\0r\0\x61\0\x44\0\x42\x1\0\0\x3\xfa\xff\xff\xff\xff\0\0\0\0\0\0\0\0)

[SQLLogDock]
Log=Application

[SchemaDock]
dropEnquotedNames=true
dropQualifiedNames=false
dropSelectQuery=true

[editor]
splitter1_sizes=@Invalid()
splitter2_sizes=@Invalid()

[importcsv]
encoding=UTF-8
firstrowheader=false
localconventions=false
quotecharacter=@Variant(\0\0\0\a\0\")
separatetables=false
separator="@Variant(\0\0\0\a\0,)"
trimfields=true
